"""edit moles file 

Revision ID: 20332b95d64b
Revises: 5a60d6eb5d06
Create Date: 2019-02-28 13:20:40.251569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20332b95d64b'
down_revision = '5a60d6eb5d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'posted')
    # ### end Alembic commands ###
