"""add category

Revision ID: 3896825dd0c3
Revises: 3905ce566490
Create Date: 2019-02-27 11:43:33.916142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3896825dd0c3'
down_revision = '3905ce566490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('votes', sa.Integer(), nullable=True))
    op.drop_column('comments', 'description')
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'category')
    op.add_column('comments', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('comments', 'votes')
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
